#!/bin/bash

# displays urls

file="temp" # packet file - generated by ./derv.sh

# last variable, so we don't print out the same url 
#   over and over, gotta make it 'weird'
last="hurrdurrdederpdurpderp"

# if the temporary packet file exists
if [ -f $file ]; then
  
  # grep the file for all lines that contain GET and Host:
  # loop through each of these lines
  cat $file | grep -a "GET\|Host\: " | sed 's/[^a-zA-Z0-9&$@?!.,-:;#%*+=]//g' | while read line; do
    
    # if the current line is the GET line  
    if [[ `echo "$line" | grep -i "GET"` != "" ]]; then
      
      # extract out everything leading up to the GET - it's usually loaded with POSTDATA
      line=${line##*GET}
      
      # remove the GET and HTTP/1.1
      site=$(echo $line | sed 's/GET //g')
      site=$(echo $site | sed 's/HTTP\/1\.1//g')
      
      # at this point, $site contains just the directory of the url, not the domain
    else
      # $line contains Host: - therefore the domain
      
      # remove Host: from $line
      site=$(echo $line | sed 's/Host://g')"$site"
      
      # if this url isn't contained in the same url we just posted
      if [[ `echo "$site" | grep -i "$last"` == "" ]]; then
        
        # ext is the last 4 characters of the url - file extension
        ext=${site:${#site}-4}
        
        # if the file is NOT a picture or any other file we don't want to see...
        if [[ $ext != .gif ]] && 
           [[ $ext != .css ]] && 
           [[ $ext != .jpg ]] && 
           [[ $ext != .png ]] && 
           [[ $ext != .ico ]] && 
           [[ $ext != *.js ]] && 
           [[ $ext != .php ]] && 
           [[ $ext != jpeg ]]; then
          # if the site is less than 65 letters long, print it!
          if [ ${#site} -lt 65 ]; then
            echo $site 
            # site=${site:0:65}
            
            last=$site
          fi
        fi
      fi
    fi
  done
  
fi

exit 0