.TH "breakpoint" 1 "Tue Sep 4 2018" "Version 2.7.1" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
\fBbreakpoint\fP -- Launch debug mode 

.PP
.SS "Synopsis"
.PP
.nf

\fBbreakpoint\fP
.fi
.PP
.SS "Description"
\fCbreakpoint\fP is used to halt a running script and launch an interactive debugging prompt\&.
.PP
For more details, see \fCDebugging fish scripts\fP in the \fCfish\fP manual\&.
.PP
There are no parameters for \fCbreakpoint\fP\&. 
