.TH "continue" 1 "Tue Sep 4 2018" "Version 2.7.1" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
\fBcontinue\fP -- skip the remainder of the current iteration of the current inner loop 

.PP
.SS "Synopsis"
.PP
.nf

LOOP_CONSTRUCT; [COMMANDS\&.\&.\&.;] \fBcontinue\fP; [COMMANDS\&.\&.\&.;] \fBend\fP
.fi
.PP
.SS "Description"
\fCcontinue\fP skips the remainder of the current iteration of the current inner loop, such as a \fCfor\fP loop or a \fCwhile\fP loop\&. It is usually added inside of a conditional block such as an \fCif\fP statement or a \fCswitch\fP statement\&.
.SS "Example"
The following code removes all tmp files that do not contain the word smurf\&.
.PP
.PP
.nf

\fBfor\fP i \fBin\fP *\&.tmp
    \fBif\fP \fBgrep\fP smurf $i
        \fBcontinue\fP
    \fBend\fP
    \fBrm\fP $i
\fBend\fP
.fi
.PP
 
