.TH "dirs" 1 "Tue Sep 4 2018" "Version 2.7.1" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
\fBdirs\fP -- print directory stack 

.PP
.SS "Synopsis"
.PP
.nf

\fBdirs\fP
\fBdirs\fP -c
.fi
.PP
.SS "Description"
\fCdirs\fP prints the current directory stack, as created by the \fC\fCpushd\fP\fP command\&.
.PP
With '-c', it clears the directory stack instead\&.
.PP
\fCdirs\fP does not accept any parameters\&. 
