.TH "exit" 1 "Tue Sep 4 2018" "Version 2.7.1" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
\fBexit\fP -- exit the shell 

.PP
.SS "Synopsis"
.PP
.nf

\fBexit\fP [STATUS]
.fi
.PP
.SS "Description"
\fCexit\fP causes fish to exit\&. If \fCSTATUS\fP is supplied, it will be converted to an integer and used as the exit code\&. Otherwise, the exit code will be that of the last command executed\&.
.PP
If exit is called while sourcing a file (using the \fCsource\fP builtin) the rest of the file will be skipped, but the shell itself will not exit\&. 
