.TH "fish_vi_mode" 1 "Tue Sep 4 2018" "Version 2.7.1" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
\fBfish_vi_mode\fP -- Enable vi mode 

.PP
.SS "Synopsis"
.PP
.nf

\fBfish_vi_mode\fP
.fi
.PP
.SS "Description"
This function is deprecated\&. Please call \fCfish_vi_key_bindings directly\fP
.PP
\fCfish_vi_mode\fP enters a vi-like command editing mode\&. To always start in vi mode, add \fCfish_vi_mode\fP to your \fCconfig\&.fish\fP file\&. 
