.TH "fish_update_completions" 1 "Tue Sep 4 2018" "Version 2.7.1" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
\fBfish_update_completions\fP -- Update completions using manual pages 

.PP
.SS "Description"
\fCfish_update_completions\fP parses manual pages installed on the system, and attempts to create completion files in the \fCfish\fP configuration directory\&.
.PP
This does not overwrite custom completions\&.
.PP
There are no parameters for \fCfish_update_completions\fP\&. 
