.TH "pwd" 1 "Tue Sep 4 2018" "Version 2.7.1" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
\fBpwd\fP -- output the current working directory 

.PP
.SS "Synopsis"
.PP
.nf

\fBpwd\fP
.fi
.PP
.SS "Description"
\fCpwd\fP outputs (prints) the current working directory\&.
.PP
Note that \fCfish\fP always resolves symbolic links in the current directory path\&. 
