.TH "vared" 1 "Tue Sep 4 2018" "Version 2.7.1" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
\fBvared\fP -- interactively edit the value of an environment variable 

.PP
.SS "Synopsis"
.PP
.nf

\fBvared\fP VARIABLE_NAME
.fi
.PP
.SS "Description"
\fCvared\fP is used to interactively edit the value of an environment variable\&. Array variables as a whole can not be edited using \fCvared\fP, but individual array elements can\&.
.SS "Example"
\fCvared PATH[3]\fP edits the third element of the PATH array 
